### ISSUE TITLE
Can not download lib 

### ISSUE THREAD

**Issue by MahmoudMabrok** [duolingo/rtl-viewpager#29]
### Required Information

i got this error `ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.duolingo.open:rtl-viewpager:2.0.0.`

### Issue Description
add lib depencecy 
`implementation 'com.duolingo.open:rtl-viewpager:2.0.0'`

**Comment by DavidDTA** [comment]
This is likely due to not including `jcenter` in the repositories in your gradle file.  However, this library is now deprecated and we do not recommend you use it for further development.  Please use [ViewPager2](https://developer.android.com/training/animation/vp2-migration) instead of this library.
